name: deploy
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - run: bun install
      - run: bun run build
      - name: Deploy 🚀
          uses: JamesIves/github-pages-deploy-action@v4
          with:
            folder: dist
