---
name: Test Client Builds

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, reopened]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        working-directory: ./coach
        run: bun install

      - name: Build project
        working-directory: ./coach
        run: bun run build